FROM 10.103.129.81:5000/alpine:latest
MAINTAINER xiaoxia_yu <xiaoxia_yu@foxitsoftware.com>

RUN mkdir /foxitqa
ADD ./PlatformCacheService /foxitqa/PlatformCacheService

WORKDIR /foxitqa
#CMD [ "/bin/sh", "-c", "./PlatformCacheService -ports=32500 -apiserver=10.103.129.81:8080"] 
