apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis
    redis-sentinel: "true"
    role: master
  name: redis-master
spec:
  containers:
    - name: master
      image: 10.103.129.81:5000/fxqa-redis:v1
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.1"
          memory: 2048Mi
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
    - name: sentinel
      image: 10.103.129.81:5000/fxqa-redis:v1
      env:
        - name: SENTINEL
          value: "true"
      ports:
        - containerPort: 26379
  nodeSelector:
    SET: platform
  volumes:
    - name: data
      emptyDir: {}
